### ISSUE TITLE
Documentation for configuration

### ISSUE THREAD

**Issue by steffanboodhoo** [dongri/mongri#3]
Was trying to configure to use locally,
Attempt:
Mongo.json
- changed 'uri' value to suit mine, (tested)
  Auth.json
- changed 'enabled' value to true, (tested) 
  Edit:
  Undid change to Mongo.json 'uri', changed mine to suit, (tested) 

Can you give some assistance by stating what files>values to change to connect to a local mongodb instance, thanks

**Comment by sksullivan** [comment]
+1

**Comment by ppalucha** [comment]
I was able to run it with my local database like this:

Add entry in config/mongo.js pointing to your database:

```
{
  "your_database": {
    "uri": "mongodb://localhost:27017/your_database",
    "opts": {
      "replset": {
        "rs_name": "mongri-repl",
        "readPreference": "secondaryPreferred",
        "poolsize": 20,
        "socketOptions": {
          "keepAlive": 1
        }
      }
    }
  }
}
```
Add entry in config/auth.json for your database (google section is required even if not enabled):

```
{
  "your_database":{
    "basic": {
      "enabled": false,
      "name": "mongri",
      "pass": "password"
    },
    "google": {
      "enabled": false,
      "allow_domain": "domain.com",
      "client_id": "--insert-google-client-id-here--",
      "client_secret": "--insert-google-client-secret-here--",
      "callback_url": "http://localhost:3000/auth/google/callback"
    }
  }
}
```

Finally start application with NODE_ENV environment variable pointing to your database name:

`env NODE_ENV=fusion_demo node app.js`
